logger:
  file:
    path: /var/log/open5gs/udm.log

global:
  max:
    ue: 1024

udm:
  hnet:
    - id: 1
      scheme: 1
      key: /etc/open5gs/hnet/curve25519-1.key
    - id: 2
      scheme: 2
      key: /etc/open5gs/hnet/secp256r1-2.key
  sbi:
    server:
      - address: 0.0.0.0
        port: 7777
        advertise: udm
    client:
      scp:
        - uri: http://scp:7777
