#!/usr/bin/env python3
"""Generate the complete raw-data appendix for SRSRAN_RESULTS.md.

Every number is read from the result JSON at generation time — nothing is typed
by hand, for the same reason analysis/registry.py exists. Re-run after any new
experiment lands and the appendix regenerates in full.

    .venv/bin/python analysis/gen_raw_appendix.py > /tmp/appZ.md
"""
from __future__ import annotations
import json, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "srsran" / "results"
o = []; w = o.append


def load(n):
    p = RES / n
    if not p.exists():
        return None
    try:
        return json.loads(p.read_text())
    except json.JSONDecodeError:
        return None


def f(x, nd=3):
    """Format a value for a table cell.

    NOTE: the trailing-zero strip must only run when a decimal point is present.
    Without that guard, f(90.0, nd=0) produced "9" and f(1000.0, nd=0) produced
    "1" — rstrip("0") happily eats the trailing zeros of an integer. It silently
    corrupted every elapsed_s in the raw appendix before it was caught.
    """
    if x is None: return "—"
    if isinstance(x, bool): return "yes" if x else "no"
    if isinstance(x, float):
        t = f"{x:.{nd}f}"
        return t.rstrip("0").rstrip(".") if "." in t else t
    return str(x)


w("\n---\n")
w("# APPENDIX Z — COMPLETE RAW DATA, EVERY EXPERIMENT\n")
w("Generated by `analysis/gen_raw_appendix.py` directly from the result JSON files.\n"
  "No figure here is transcribed by hand. Regenerate after any new run.\n")

# ── E0.1 ──────────────────────────────────────────────────────────────────
d = load("E0_1_ambr_enforcement.json")
a = load("E0_1_analysis.json")
w("\n## Z.1 — E0.1 AMBR enforcement verification\n")
if not d: w("*(no data)*\n")
else:
    w(f"n_ue {d.get('n_ue')} · {d.get('duration_s')}s per point · tolerance "
      f"{d.get('tolerance')} · sweep {d.get('sweep_mbps')}\n")
    for arm in [k for k in d if k.startswith("arm_")]:
        rows = d[arm]
        if not isinstance(rows, list) or not rows: continue
        label = arm.replace("arm_", "")
        w(f"\n**Arm `{label}`** — {'native 5G AMBR signalling' if 'native' in label else 'declared HTB QER stand-in'}\n")
        w("| requested AMBR | achieved Mbps | rel. error | tracks? | UE IP |")
        w("|---|---|---|---|---|")
        for r in rows:
            w(f"| {f(r.get('ambr_mbps'))} | {f(r.get('achieved_mbps'))} | "
              f"{f(r.get('rel_err'))} | {f(r.get('tracks'))} | {r.get('ue_ip','—')} |")
        n_ok = sum(1 for r in rows if r.get("tracks"))
        w(f"\n**{n_ok}/{len(rows)} points track the requested ceiling.**\n")
    if a:
        w("\n**Analysis:**\n")
        for k, v in a.items():
            if isinstance(v, str): w(f"- **{k}** — {v}")
        w("")

# ── E0.2 ──────────────────────────────────────────────────────────────────
d = load("E0_2_scale.json")
w("\n## Z.2 — E0.2 multi-UE scale\n")
if not d: w("*(no data)*\n")
else:
    rows = d.get("rows") or d.get("results") or []
    if rows and isinstance(rows, list):
        keys = [k for k in rows[0] if not isinstance(rows[0][k], (dict, list))]
        w("| " + " | ".join(keys) + " |"); w("|" + "---|" * len(keys))
        for r in rows: w("| " + " | ".join(f(r.get(k)) for k in keys) + " |")
    else:
        w("```json"); w(json.dumps(d, indent=2)[:2500]); w("```")
    w("")

# ── E0.3 ──────────────────────────────────────────────────────────────────
d = load("E0_3_capacity.json")
w("\n## Z.3 — E0.3 capacity C\n")
if not d: w("*(no data)*\n")
else:
    w(f"- n_ue **{d['n_ue']}** · window **{d['window_s']} s** · all AMBRs unlimited")
    w(f"- **C = {d['C_mbps']} Mbps** aggregate · fair share **{d['fair_share_mbps']} Mbps**")
    rec = d.get("record", {})
    w(f"- λ = {f(rec.get('lambda_ms'))} ms · ρ = {f(rec.get('rho_pct'))}% · σ = {f(rec.get('sigma'))}")
    per = rec.get("per_ue_tau") or {}
    if per:
        w("\n| UE | τ (Mbps) |"); w("|---|---|")
        for k, v in per.items(): w(f"| {k} | {f(v)} |")
    w("")

# ── E0.4 ──────────────────────────────────────────────────────────────────
d = load("E0_4_two_regime.json")
w("\n## Z.4 — E0.4 two-regime sweep (every point)\n")
if not d: w("*(no data)*\n")
else:
    w(f"C = {d['C_mbps']} Mbps · knee = {d['knee_mbps_per_ue']} Mbps/UE · n = {d['n_ue']}\n")
    w("| B/UE | offered | regime | τ agg | τ/UE | λ ms | ρ % | σ | complete |")
    w("|---|---|---|---|---|---|---|---|---|")
    for r in d["rows"]:
        t = r.get("tau_mbps")
        w(f"| {f(r['B_mbps_per_ue'])} | {f(r['offered_total_mbps'])} | {r['regime']} | "
          f"{f(t)} | {f(t/d['n_ue']) if t else '—'} | {f(r.get('lambda_ms'))} | "
          f"{f(r.get('rho_pct'))} | {f(r.get('sigma'))} | {f(r.get('complete'))} |")
    if d.get("verdict"):
        w(f"\n**Verdict:** `{json.dumps(d['verdict'])}`")
    w(f"\n**Degeneracy check:** {d.get('degeneracy_check','—')}\n")

# ── E0.5 ──────────────────────────────────────────────────────────────────
d = load("E0_5_analysis.json")
w("\n## Z.5 — E0.5 ρ and σ, per-UE detail for both RLC arms\n")
if not d: w("*(no data)*\n")
else:
    for arm in ("am", "um"):
        A = d["arms"].get(arm)
        if not A: continue
        w(f"\n**RLC {arm.upper()}** — offered {A['offered_total_mbps']} Mbps → "
          f"delivered {A['delivered_total_mbps']} Mbps · "
          f"iperf3 loss {A['iperf_loss_mean_pct']}% · **counter loss {A['counter_loss_mean_pct']}%**\n")
        w("| UE | offered Mbps | iperf3 loss % | tun_srsue rx Mbps | counter loss % |")
        w("|---|---|---|---|---|")
        for r in A["per_ue"]:
            w(f"| {r['ue']} | {f(r['offered_mbps'])} | {f(r['iperf_loss_pct'])} | "
              f"{f(r['tun_rx_mbps'])} | {f(r['counter_loss_pct'])} |")
    w(f"\n**Comparison:** `{json.dumps(d['comparison'])}`\n")
    for k, v in d["conclusions"].items():
        w(f"- **{k}** — {v}")
    w(f"\n**σ test:** `{json.dumps(d.get('sigma_test'))}`\n")

# ── E1 ────────────────────────────────────────────────────────────────────
d = load("E1_harm_mechanism.json")
w("\n## Z.6 — E1 asymmetric harm (every sweep point, per-UE)\n")
if not d: w("*(no data)*\n")
else:
    w(f"C = {d['C_mbps']} Mbps · baseline {d['baseline_mbps']} Mbps/UE · "
      f"aggressor **{d['aggressor']}** · victims {d['victims']}")
    w(f"\nFixed for the whole campaign: {', '.join(d['fixed_during_campaign'])}\n")
    w("| ue1 AMBR | ×baseline | τ aggressor | τ victim mean | τ total | λ ms | ρ % | Q victim | Q aggr | ΔQ victim |")
    w("|---|---|---|---|---|---|---|---|---|---|")
    for r in d["rows"]:
        w(f"| {f(r['ue1_ambr_mbps'])} | {f(r['ratio_to_baseline'])} | {f(r.get('tau_aggressor'))} | "
          f"{f(r.get('tau_victim_mean'))} | {f(r.get('tau_total'))} | {f(r.get('lambda_ms'))} | "
          f"{f(r.get('rho_pct'))} | {f(r.get('Q_victim'))} | {f(r.get('Q_aggressor'))} | "
          f"{f(r.get('dQ_victim'))} |")
    w("\n**Per-UE throughput at every point:**\n")
    w("| ue1 AMBR | " + " | ".join(sorted((d['rows'][0].get('per_ue_tau') or {}).keys())) + " |")
    ks = sorted((d['rows'][0].get('per_ue_tau') or {}).keys())
    w("|" + "---|" * (len(ks) + 1))
    for r in d["rows"]:
        per = r.get("per_ue_tau") or {}
        w(f"| {f(r['ue1_ambr_mbps'])} | " + " | ".join(f(per.get(k)) for k in ks) + " |")
    w(f"\n**Verdict:** `{json.dumps(d.get('verdict'))}`")
    w(f"\n**Degeneracy check:** {d.get('degeneracy_check','—')}\n")

sys.stdout.write("\n".join(o) + "\n")

# ── appended: Z.7 onward ──────────────────────────────────────────────────
o2 = []; w = o2.append

# E2
d = load("E2_contamination.json")
w("\n## Z.7 — E2 contamination channel (all 30 writes per arm)\n")
if not d: w("*(no data)*\n")
else:
    for arm in ("standard", "isolated"):
        A = d.get(f"arm_{arm}")
        if not A: continue
        w(f"\n**{arm} collector** — corr {f(A.get('corr_write_readback'))} · "
          f"distinct readbacks {A.get('distinct_readbacks')} · "
          f"true contamination {f(A.get('true_contamination_rate'))}\n")
        w("| # | write Mbps | readback | naive match | provenance tag |")
        w("|---|---|---|---|---|")
        for i, r in enumerate(A["rows"], 1):
            w(f"| {i} | {f(r['write_mbps'])} | {f(r['readback'])} | "
              f"{f(r['reappeared'])} | {f(r['tagged'])} |")
        if A.get("naive_rate_note"): w(f"\n> {A['naive_rate_note']}\n")
    e = d.get("E2_3_dR_at_fixed_phi") or {}
    w(f"\n**E2.3** — R {f(e.get('R_before'))} → {f(e.get('R_after'))}, "
      f"ΔR **{f(e.get('delta_R'))}** · Φ deltas `{json.dumps(e.get('phi_deltas'))}`")
    w(f"\n> **{e.get('phi_verification_status','—')}** — {e.get('phi_verification_note','')}\n")
    k = d.get("E2_4_standards_shaped_kpi") or {}
    w(f"\n**E2.4** — `{k.get('kpi')}` value {f(k.get('value'))} · "
      f"provenance field present: {f(k.get('provenance_field_present'))}")
    w(f"\n> {k.get('validity_note','')}\n")

# E4
d = load("E4_scripted_controller.json")
w("\n## Z.8 — E4 deterministic controller (per-arm, with a full session trace)\n")
if not d: w("*(no data)*\n")
else:
    w(f"baseline {d['baseline_mbps']} Mbps · step ×{d['escalation_step']} · "
      f"max steps {d['max_steps']} · rule: *{d['decision_rule']}*\n")
    w("| arm | collector | acts on readback | n | mean steps | mean final AMBR | ×baseline | hit ceiling | stop reasons |")
    w("|---|---|---|---|---|---|---|---|---|")
    for arm, A in d["arms"].items():
        w(f"| {arm} | {'isolated' if A['isolated_collector'] else 'standard'} | "
          f"{f(A['acts_on_readback'])} | {A['n']} | {f(A['mean_steps'])} | "
          f"{f(A['mean_final_ambr_mbps'])} | {f(A['mean_escalation_factor'])}× | "
          f"{A['sessions_hitting_ceiling']}/{A['n']} | `{json.dumps(A.get('stop_reasons'))}` |")
    cl = d["arms"].get("closed_loop", {}).get("sessions", [])
    if cl:
        w("\n**Representative closed-loop session (session 1), every step:**\n")
        w("| step | wrote Mbps | accepted | readback | analytics confirmed |")
        w("|---|---|---|---|---|")
        for t in cl[0]["trace"]:
            w(f"| {t['step']} | {f(t['wrote_mbps'])} | {f(t.get('accepted'))} | "
              f"{f(t.get('readback'))} | {f(t.get('analytics_confirmed'))} |")
    iso = d["arms"].get("closed_loop_iso", {}).get("sessions", [])
    if iso:
        w("\n**Representative closed-loop + ISO session (session 1) — terminates at step 1:**\n")
        w("| step | wrote Mbps | accepted | readback | analytics confirmed |")
        w("|---|---|---|---|---|")
        for t in iso[0]["trace"]:
            w(f"| {t['step']} | {f(t['wrote_mbps'])} | {f(t.get('accepted'))} | "
              f"{f(t.get('readback'))} | {f(t.get('analytics_confirmed'))} |")
    w(f"\n**Verdict:** {d['verdict']['conclusion']}\n")

# E5
d = load("E5_multivariable.json")
w("\n## Z.9 — E5 generality: every write and readback, all four variables\n")
if not d: w("*(no data)*\n")
else:
    for label, key in (("standard collector", "channel_standard"),
                       ("IsolatedCollector", "channel_isolated")):
        w(f"\n### {label}\n")
        for var, V in d[key].items():
            w(f"\n**`{var}`** → analytic `{V['metric']}` · exact "
              f"{V['exact_matches']}/{V['n']} · corr {f(V.get('corr_write_readback'))} · "
              f"field present {f(V['field_present'])} · **channel open {f(V['channel_open'])}**\n")
            w("| # | write | readback |"); w("|---|---|---|")
            for i, (a_, b_) in enumerate(zip(V["writes"], V["readbacks"]), 1):
                w(f"| {i} | {f(a_)} | {f(b_)} |")
    w(f"\n**Variables under test:**\n")
    for k, v in d["variables"].items(): w(f"- `{k}` — {v}")
    w(f"\n**{d['channel_open_standard']} channels open standard · "
      f"{d['channel_open_isolated']} isolated**\n")
    for k in ("channel_evidence", "IMPORTANT_SEPARATION", "defense_bug_found"):
        if d["verdict"].get(k): w(f"\n**{k}** — {d['verdict'][k]}\n")

# E8
d = load("E8_gate_replay.json")
w("\n## Z.10 — E8 gate replay, every gate × attack × dilation\n")
if not d: w("*(no data)*\n")
else:
    w(f"baseline {d['baseline_mbps']} Mbps · θ = {d['theta']}× · "
      f"{d['calls_per_trace']} calls/trace · gate params `{json.dumps(d['gate_parameters'])}`\n")
    w("| gate | state variable | attack | dilation | spacing s | allowed | rejected | max AMBR | ×baseline | exceeded θ |")
    w("|---|---|---|---|---|---|---|---|---|---|")
    for r in d["results"]:
        w(f"| {r['gate']} | {r['state_variable']} | {r['attack']} | {r['dilation']}× | "
          f"{f(r['spacing_s'])} | {r['allowed']} | {r['rejected']} | "
          f"{f(r['max_ambr_reached_mbps'])} | {f(r['escalation_factor'])}× | "
          f"{f(r['exceeded_theta'])} |")
    w(f"\n**Evaded:** {d['verdict']['gates_evaded_under_some_attack']}")
    w(f"\n**Held:** {d['verdict']['gates_holding_under_every_attack']}")
    w(f"\n\n{d['verdict']['conclusion']}\n")

# E10
d = load("E10_overhead.json")
w("\n## Z.11 — E10 overhead, full distributions\n")
if not d: w("*(no data)*\n")
else:
    w(f"n = {d['n_per_arm']} per arm · management-plane reference interval "
      f"{d['mgmt_plane_interval_ms']} ms\n")
    w("| arm | drift | ISO | n | mean | p50 | p95 | p99 | min | max | stdev |")
    w("|---|---|---|---|---|---|---|---|---|---|---|")
    for arm, A in d["arms"].items():
        w(f"| {arm} | {f(A['drift_bound'])} | {f(A['isolated_collector'])} | {A['n']} | "
          f"{f(A['mean_ms'])} | {f(A['p50_ms'])} | {f(A['p95_ms'])} | {f(A['p99_ms'])} | "
          f"{f(A['min_ms'])} | {f(A['max_ms'])} | {f(A['stdev_ms'])} |")
    k = d["kpi_query_latency"]
    w(f"\n**KPI query latency** — n {k['n']} · mean {f(k['mean_ms'])} · p50 {f(k['p50_ms'])} · "
      f"p95 {f(k['p95_ms'])} · p99 {f(k['p99_ms'])} ms\n")
    w("| arm | Δ vs none ms | Δ % vs none | % of 1 s mgmt interval |")
    w("|---|---|---|---|")
    for arm, x in d["deltas_vs_none"].items():
        w(f"| {arm} | {f(x['delta_ms'])} | {f(x['delta_pct_vs_none'])} | "
          f"{f(x['pct_of_mgmt_plane_interval'], 4)} |")
    w(f"\n> **{d['verdict'].get('measurement_floor_caveat','')}**\n")
    w(f"\n> {d['verdict'].get('defensible_claim','')}\n")

# E12 / E12b
d = load("E12_qoe_mapping.json")
w("\n## Z.12 — E12 QoE mapping, every Φ point (both sources)\n")
if not d: w("*(no data)*\n")
else:
    w(f"ladder `{json.dumps(d['ladder'])}` · segment {d['segment_s']}s · "
      f"session {d['session_s']}s · buffer target {d['buffer_target_s']}s · "
      f"ABR safety {d['abr_safety_factor']}\n")
    w("| source | x | regime | τ/UE | λ ms | ρ % | rep | stalls | rebuffer | MOS stream | one-way ms | R factor | MOS conv | Q net |")
    w("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|")
    for r in d["rows"]:
        w(f"| {r['source']} | {f(r['x'])} | {r['regime']} | {f(r['tau_per_ue_mbps'])} | "
          f"{f(r['lambda_ms'])} | {f(r.get('rho_pct'))} | {r['selected_representation']} | "
          f"{r['stall_count']} | {f(r['rebuffer_ratio'])} | {f(r['mos_estimate'])} | "
          f"{f(r.get('one_way_delay_ms'))} | {f(r.get('R_factor'))} | "
          f"{f(r.get('mos_conversational'))} | {f(r['Q_network'])} |")
    for k in ("which_layer_definition_3_uses", "why_network_layer", "THE_KEY_FINDING",
              "what_this_means_for_the_harm_claim", "conformance"):
        if d["verdict"].get(k): w(f"\n**{k}** — {d['verdict'][k]}\n")

d = load("E12b_q_sensitivity.json")
w("\n## Z.13 — E12b Q-normaliser sensitivity\n")
if not d: w("*(no data)*\n")
else:
    e = d["endpoints"]
    w(f"τ {f(e['tau_first'])} → {f(e['tau_last'])} Mbps · "
      f"λ {f(e['lambda_first'])} → {f(e['lambda_last'])} ms · τ_norm {d['tau_norm_mbps']}\n")
    w("| λ normaliser ms | Q first | Q last | ΔQ | drop % | λ term floored |")
    w("|---|---|---|---|---|---|")
    for r in d["rows"]:
        w(f"| {f(r['lambda_norm_ms'])} | {f(r['Q_first'], 4)} | {f(r['Q_last'], 4)} | "
          f"{f(r['dQ'], 4)} | {f(r['drop_pct'])} | {f(r['lambda_term_floored_at_last_point'])} |")
    for k in ("FINDING", "WHAT_SURVIVES", "RECOMMENDED_WORDING"):
        w(f"\n**{k}** — {d['verdict'][k]}\n")

# registry
try:
    reg = json.loads((ROOT / "analysis" / "paper_numbers.json").read_text())
except Exception:
    reg = None
w("\n## Z.14 — E11 complete number registry (every paper number)\n")
if not reg: w("*(no data)*\n")
else:
    w(f"{len(reg)} numbers · `analysis/verify_paper.py` recomputes all and exits 0.\n")
    w("| key | value | units | n | baseline key | robust | source |")
    w("|---|---|---|---|---|---|---|")
    for k in sorted(reg):
        v = reg[k]
        w(f"| `{k}` | {f(v['value'], 4)} | {v['units']} | {f(v.get('n'))} | "
          f"{('`'+v['baseline_key']+'`') if v.get('baseline_key') else '—'} | "
          f"{'yes' if v['robust_to_analysis_choices'] else '**NO**'} | `{v['source']}` |")
    nr = [k for k in reg if not reg[k]['robust_to_analysis_choices']]
    if nr:
        w(f"\n**Numbers flagged NOT robust to analysis choices ({len(nr)}) — never quote these as solid:**\n")
        for k in sorted(nr):
            w(f"\n- `{k}` = {reg[k]['value']} {reg[k]['units']}\n  — {reg[k]['note']}")
    w("")

sys.stdout.write("\n".join(o2) + "\n")

# ── appended: LLM experiments raw cells ───────────────────────────────────
o3 = []; w = o3.append
import glob as _g

def _cells(exp):
    out = []
    for f in _g.glob(str(ROOT / "srsran" / "results" / "llm_trials" / exp / "*.json")):
        try:
            out.append(json.loads(Path(f).read_text()))
        except json.JSONDecodeError:
            pass
    return sorted(out, key=lambda c: c.get("trial", 0))

# E3
cells = _cells("E3")
w("\n## Z.15 — E3 attribution: every trial\n")
if not cells:
    w("*(no data)*\n")
else:
    ok = [c for c in cells if not c.get("error")]
    w(f"{len(cells)} cells, {len(cells)-len(ok)} errors. Arms V/ISO complete; BUD/FULL in progress.\n")
    w("\n> Stage B, Stage D and circuit closure are **zero by construction** under ISO "
      "(the `ambr_dl_mean` field is absent), so they are shown for completeness but "
      "carry no evidential weight in that arm.\n")
    w("\n| # | arm | register | B★ | B_final | Δ★ | k★ | calls | committed | after k★ | A | B | C | D | closed | s |")
    w("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|")
    for c in cells:
        if c.get("error"):
            w(f"| {c.get('trial')} | {c.get('arm','?')} | {c.get('register','?')} | "
              f"colspan ERROR: {str(c['error'])[:60]} |||||||||||")
            continue
        y = lambda k: "Y" if c.get(k) else "·"
        w(f"| {c['trial']} | {c['arm']} | {c['register']} | "
          f"{f(c.get('b_star_mbps'))} | {f(c.get('b_final_mbps'))} | "
          f"{f(c.get('delta_star'), 4)} | {f(c.get('k_star_call_index'))} | "
          f"{c.get('n_policy_calls')} | {len(c.get('policy_values_mbps') or [])} | "
          f"{f(c.get('agent_attributable_writes'))} | "
          f"{y('stage_A_decomposed')} | {y('stage_B_contaminated')} | "
          f"{y('stage_C_self_confirmed')} | {y('stage_D_escalated_on_readback')} | "
          f"{y('circuit_closed')} | {f(c.get('elapsed_s'),0)} |")
    w("\n**Every committed AMBR value, per trial (Mbps):**\n")
    w("\n| # | arm | register | sequence of committed writes |")
    w("|---|---|---|---|")
    for c in ok:
        v = c.get("policy_values_mbps") or []
        w(f"| {c['trial']} | {c['arm']} | {c['register']} | "
          f"{' → '.join(str(int(x)) for x in v) if v else '*(none committed)*'} |")

for exp, title in (("E9", "E9 benign cost"), ("E5", "E5 Part 2 failure generality"),
                   ("E7", "E7 register study"), ("E6", "E6 capability sweep")):
    cells = _cells(exp)
    w(f"\n## Z.{16 + ['E9','E5','E7','E6'].index(exp)} — {title}: every trial\n")
    if not cells:
        w("*(not yet run)*\n"); continue
    ok = [c for c in cells if not c.get("error")]
    w(f"{len(cells)} cells, {len(cells)-len(ok)} errors.\n")
    lbls = [k for k in ("arm", "register", "variable", "tier", "model_name", "intent_idx")
            if any(k in c for c in ok)]
    w("\n| # | " + " | ".join(lbls) + " | B_final | Δ★ | calls | committed | A | B | C | D | closed | s |")
    w("|---|" + "---|" * (len(lbls) + 10))
    for c in ok:
        y = lambda k: "Y" if c.get(k) else "·"
        w(f"| {c['trial']} | " + " | ".join(str(c.get(k, '—')) for k in lbls) + " | "
          f"{f(c.get('b_final_mbps'))} | {f(c.get('delta_star'),4)} | "
          f"{c.get('n_policy_calls')} | {len(c.get('policy_values_mbps') or [])} | "
          f"{y('stage_A_decomposed')} | {y('stage_B_contaminated')} | "
          f"{y('stage_C_self_confirmed')} | {y('stage_D_escalated_on_readback')} | "
          f"{y('circuit_closed')} | {f(c.get('elapsed_s'),0)} |")

sys.stdout.write("\n".join(o3) + "\n")
